FROM python:3.11.3-alpine

RUN apk add --no-cache git

WORKDIR /app

RUN git clone https://github.com/arc986/testFlask.git /app

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 80

ENTRYPOINT [ "python" ]

CMD [ "-m", "flask", "--app", "app", "run", "--host=0.0.0.0" ]
